const experiences = [
  {
    title: "Pengembang Web React.js",
    company_name: "TechPro Innovations",
    icon: starbucks,
    iconBg: "#007BFF",
    date: "Juni 2018 - September 2021",
    points: [
      "Memimpin pengembangan aplikasi web mutakhir menggunakan React.js, Redux, dan GraphQL.",
      "Mengimplementasikan alat visualisasi data untuk analisis real-time, meningkatkan pemahaman pengguna.",
      "Bekerja erat dengan desainer UX/UI untuk menciptakan antarmuka pengguna yang intuitif dan responsif.",
      "Membimbing pengembang junior dan mengadakan workshop untuk meningkatkan keterampilan tim.",
    ],
  },
  {
    title: "Ilmuwan Data (Data Scientist)",
    company_name: "RedFields Inc.",
    icon: tesla,
    iconBg: "#6A1B9A",
    date: "Oktober 2021 - Desember 2022",
    points: [
      "Menggunakan Python dan model statistik canggih untuk menganalisis rangkaian data kompleks, memberikan wawasan yang dapat diimplementasikan kepada klien.",
      "Mengembangkan pipa data otomatis untuk mengurangi waktu pemrosesan data sebesar 30%.",
      "Bekerjasama dengan tim lintas fungsi untuk menerjemahkan temuan data menjadi strategi bisnis yang dapat diimplementasikan.",
      "Menghadirkan rekomendasi berbasis data kepada pemangku kepentingan eksekutif untuk pengambilan keputusan strategis.",
    ],
  },
  {
    title: "Pengembang Aplikasi Mobile (React Native)",
    company_name: "PT. Inovasi Teknologi Sejahtera",
    icon: shopify,
    iconBg: "#673AB7",
    date: "Februari 2023 - Sekarang",
    points: [
      "Merancang dan mengembangkan aplikasi mobile berfitur lengkap untuk platform Android dan iOS menggunakan Flutter dan Kotlin.",
      "Mengimplementasikan algoritma yang efisien untuk sinkronisasi data real-time, memastikan pengalaman pengguna yang lancar.",
      "Bekerjasama dengan manajer produk dan tim jaminan kualitas untuk memberikan aplikasi berkualitas tinggi tepat waktu.",
      "Tetap mengikuti tren pengembangan mobile terbaru dan mengintegrasikan fitur-fitur mutakhir ke dalam aplikasi.",
    ],
  },
  {
    title: "Pengembang Web Full Stack",
    company_name: "TokoPakEdi",
    icon: meta,
    iconBg: "#FF5722",
    date: "Mei 2020 - Desember 2021",
    points: [
      "Mengembangkan aplikasi web end-to-end, dari desain hingga peluncuran, menggunakan teknologi seperti React.js, Node.js, dan MongoDB.",
      "Mengelola basis data dan mengimplementasikan API untuk mengintegrasikan berbagai fitur aplikasi.",
      "Berpartisipasi dalam pengujian fungsional dan mengoptimalkan kinerja aplikasi.",
      "Bekerjasama dalam tim lintas fungsi untuk mencapai tujuan proyek.",
    ],
  },
  {
    title: "Analis Bisnis Data",
    company_name: "LupaBapak",
    icon: shopify,
    iconBg: "#009688",
    date: "Januari 2019 - Mei 2020",
    points: [
      "Menganalisis data operasional dan keuangan untuk mengidentifikasi peluang peningkatan efisiensi dan profitabilitas.",
      "Mengembangkan laporan dan dasbor untuk memvisualisasikan hasil analisis data.",
      "Bekerjasama dengan manajer untuk mengembangkan strategi bisnis yang didukung oleh temuan data.",
      "Membantu dalam pemilihan dan implementasi perangkat lunak analisis data.",
    ],
  },
];
